### PR TITLE
 [ ADD ] added locales to skill via gettext

### PR DESCRIPTION
**Pull request by reaganmcf**
*Description of changes:*
- Abstracted out the string responses into `alexa/data` to allow python's `gettext` functionality to automatically parse the strings to the proper locale of the user, provided in `handler_input.request_envelope`. 
- Added corresponding `LocalizationRequestInterceptor()` to attach `gettext` to `handler_input.request_attributes` before finding proper Intent handler.
- Updated `models/` with each Utterance Model corresponding to each of the support locales.

Supported Locales:
`fr-FR`, `fr-CA`, `hi-IN`, `it-IT`, `ja-JP`, `pt-BR`, `de-DE`, `en-AU`, `en-CA`, `en-IN`, `en-GB`, `es-ES`, and `es-MX`. 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by nikhilym — APPROVED** [review]
LGTM. 🚢 . Only suggestion is to add some documentation on these additional files. Without that, new skill developers would find it difficult to understand these files.

**Comment by reaganmcf** [comment]
@nikhilym Updated my PR to be more descriptive of changes

**Comment by nikhilym** [comment]
Thanks @reaganmcf . Since you are here, can you also add the internationalization instructions to the instructions folder? We have a set of instructions [here](https://github.com/alexa/skill-sample-python-fact/blob/master/instructions/localization.md)

**Comment by reaganmcf** [comment]
@nikhilym added

**Review by nikhilym — APPROVED** [review]
:shipit:

**Pull request merged**
